#!/bin/bash
# 
# XML source reading test script
#
# Copyright (C) 2010 Nikolai Kondrashov
# 
# This file is part of hidrd.
# 
# Hidrd is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# Hidrd is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with hidrd; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
# 

set -e -u -o pipefail
shopt -s nullglob

function run ()
{
    local cmd="$1"; shift
    local options="$1"; shift
    local input="$1"; shift
    local output="$1"; shift
    local test_output="$output.test"
    local status

    echo "Checking XML writing of \"$input\" against \"$output\"" \
         "with options \"$options\"..." >&2

    (
        local output_lines
        local test_output_lines
        local max_lines

        "$cmd" "$options" "$input" "$test_output"

        output_lines=`wc -l < "$output"`
        test_output_lines=`wc -l < "$test_output"`
        if (( $test_output_lines > $output_lines )); then
            max_lines=$test_output_lines
        else
            max_lines=$output_lines
        fi

        diff -u -U$max_lines "$output" "$test_output" >&2
    ) && status=$? || status=$?

    rm -f "$test_output"

    if (( $status == 0 )); then
        echo "PASSED." >&2
    else
        echo "FAILED." >&2
    fi

    return $status
}


cd xml_write_test_data

for INPUT_FILE in *.bin; do
    OPTIONS=""
    OUTPUT_FILE="${INPUT_FILE%.bin}.xml"
    OPTIONS_FILE="${INPUT_FILE%.bin}.opt"
    if [ -e "$OPTIONS_FILE" ]; then
        OPTIONS=`cat "$OPTIONS_FILE"`
    fi
    run ../hidrd_xml_write "$OPTIONS" "$INPUT_FILE" "$OUTPUT_FILE"
done


